<!doctype html>
<html ng-app="Categorias">
<head>
    <meta charset="UTF-8">
    <title>ZF2+Angularjs</title>
    <link href="css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
</head>
<body>

<div id="wrap">
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">School of net</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/">Categorias</a></li>
                    <li><a href="/">Produtos</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container" ng-controller="CategoriasCtrl">
        <div class="page-header" ng-controller="CategoriasCtrl">
            <br>
            <?php echo $this->content; ?>
            <div ng-view></div>
        </div>

        <div id="footer">
            <div class="container">
                <p class="text-muted credit">School of net</p>
            </div>
        </div>
    </div>
</div>

<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script>var $jQuery = jQuery.noConflict();</script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-route.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.2.13/angular-resource.min.js"></script>
<script src="projetoangular/Categorias.js"></script>
<script src="projetoangular/CategoriasCtrl.js"></script>
<script src="projetoangular/CategoriasSrv.js"></script>
</body>
</html>